### ISSUE TITLE
Internal server error: unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst')

### ISSUE THREAD

**Issue by catcian** [mvpyb/vite-element-admin#9]
`localhost:vite-element-admin mac$ npm run dev

> vite-element-admin@3.0.0 dev
> cross-env --max_old_space_size=4096 vite

  VITE v3.2.5  ready in 1222 ms

  ➜  Local:   http://localhost:9527/
  ➜  Network: http://192.168.31.148:9527/
unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst')
unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst') (x2)
unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst') (x3)
unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst') (x4)
unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst') (x5)
11:13:00 [vite] Internal server error: unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst')
  Plugin: unplugin-vue-define-options
  File: /Users/mac/code/gjb/tmp/vite-element-admin/src/components/YuSvgIcon/src/index.vue
      at formatError (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40281:46)
      at TransformContext.error (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40277:19)
      at TransformContext.transform (/Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+unplugin-vue-define-options@0.12.8_vue@3.2.45/node_modules/unplugin-vue-define-options/dist/chunk-TH6HNHQW.js:131:14)
      at plugin.transform (/Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+unplugin@1.0.1/node_modules/unplugin/dist/index.js:1211:25)
      at Object.transform (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40534:44)
      at loadAndTransform (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:36921:51)
unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst')
11:13:00 [vite] Internal server error: unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst')
  Plugin: unplugin-vue-define-options
  File: /Users/mac/code/gjb/tmp/vite-element-admin/src/layout/components/AppMain.vue
      at formatError (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40281:46)
      at TransformContext.error (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40277:19)
      at TransformContext.transform (/Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+unplugin-vue-define-options@0.12.8_vue@3.2.45/node_modules/unplugin-vue-define-options/dist/chunk-TH6HNHQW.js:131:14)
      at plugin.transform (/Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+unplugin@1.0.1/node_modules/unplugin/dist/index.js:1211:25)
      at Object.transform (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40534:44)
      at loadAndTransform (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:36921:51)
11:13:00 [vite] Internal server error: unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst')
  Plugin: unplugin-vue-define-options
  File: /Users/mac/code/gjb/tmp/vite-element-admin/src/layout/components/navbar/index.vue
      at formatError (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40281:46)
      at TransformContext.error (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40277:19)
      at TransformContext.transform (/Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+unplugin-vue-define-options@0.12.8_vue@3.2.45/node_modules/unplugin-vue-define-options/dist/chunk-TH6HNHQW.js:131:14)
      at plugin.transform (/Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+unplugin@1.0.1/node_modules/unplugin/dist/index.js:1211:25)
      at Object.transform (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40534:44)
      at loadAndTransform (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:36921:51)
11:13:00 [vite] Internal server error: unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst')
  Plugin: unplugin-vue-define-options
  File: /Users/mac/code/gjb/tmp/vite-element-admin/src/layout/components/settings/index.vue
      at formatError (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40281:46)
      at TransformContext.error (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40277:19)
      at TransformContext.transform (/Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+unplugin-vue-define-options@0.12.8_vue@3.2.45/node_modules/unplugin-vue-define-options/dist/chunk-TH6HNHQW.js:131:14)
      at plugin.transform (/Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+unplugin@1.0.1/node_modules/unplugin/dist/index.js:1211:25)
      at Object.transform (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40534:44)
      at loadAndTransform (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:36921:51)
11:13:00 [vite] Internal server error: unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst')
  Plugin: unplugin-vue-define-options
  File: /Users/mac/code/gjb/tmp/vite-element-admin/src/layout/components/tagsView/index.vue
      at formatError (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40281:46)
      at TransformContext.error (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40277:19)
      at TransformContext.transform (/Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+unplugin-vue-define-options@0.12.8_vue@3.2.45/node_modules/unplugin-vue-define-options/dist/chunk-TH6HNHQW.js:131:14)
      at plugin.transform (/Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+unplugin@1.0.1/node_modules/unplugin/dist/index.js:1211:25)
      at Object.transform (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40534:44)
      at loadAndTransform (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:36921:51)
11:13:00 [vite] Internal server error: unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst')
  Plugin: unplugin-vue-define-options
  File: /Users/mac/code/gjb/tmp/vite-element-admin/src/layout/components/sidebar/Logo.vue
      at formatError (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40281:46)
      at TransformContext.error (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40277:19)
      at TransformContext.transform (/Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+unplugin-vue-define-options@0.12.8_vue@3.2.45/node_modules/unplugin-vue-define-options/dist/chunk-TH6HNHQW.js:131:14)
      at plugin.transform (/Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+unplugin@1.0.1/node_modules/unplugin/dist/index.js:1211:25)
      at Object.transform (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40534:44)
      at loadAndTransform (file:///Users/mac/code/gjb/tmp/vite-element-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:36921:51)
unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst')`

**Comment by mvpyb** [comment]
npm uninstall  unplugin-vue-define-options
npm install  unplugin-vue-define-options -S
 如果是ts ，tsconfig.json 文件中types, "unplugin-vue-define-options/macros-global" 这一项替换原有的配置
